language: php

php:
  - 7.2

before_script:
  - composer install

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=clover.xml --colors
  - vendor/bin/phpcs src/ tests/

after_script:
  - sh .travis.coverage.sh
